# Generated by Django 5.2.8 on 2026-02-05 21:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre y Apellidos')),
                ('dni', models.CharField(blank=True, default='', max_length=20, verbose_name='DNI/NIE')),
                ('direccion', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10, verbose_name='C.P.')),
                ('municipio', models.CharField(blank=True, default='', max_length=100, verbose_name='Municipio')),
                ('provincia', models.CharField(blank=True, default='VALENCIA', max_length=100, verbose_name='Provincia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_activo', models.PositiveIntegerField(default=2025, verbose_name='Año activo')),
                ('tasa_basica', models.DecimalField(decimal_places=2, default=Decimal('94.05'), max_digits=8, verbose_name='Tasa Básica')),
                ('tasa_a', models.DecimalField(decimal_places=2, default=Decimal('28.87'), max_digits=8, verbose_name='Tasa A')),
                ('traslado', models.DecimalField(decimal_places=2, default=Decimal('8.67'), max_digits=8, verbose_name='Traslado')),
                ('renovacion', models.DecimalField(decimal_places=2, default=Decimal('94.05'), max_digits=8, verbose_name='Renovación')),
                ('iva_rate', models.DecimalField(decimal_places=2, default=Decimal('0.21'), max_digits=4, verbose_name='Tipo IVA')),
                ('emisor_nombre', models.CharField(default='David Carrasco Sánchez', max_length=200, verbose_name='Nombre emisor')),
                ('emisor_dni', models.CharField(default='52648389 D', max_length=20, verbose_name='DNI emisor')),
                ('emisor_domicilio', models.CharField(default='C/ Beniparrell ,31 - Bajo 9', max_length=300, verbose_name='Domicilio emisor')),
                ('emisor_cp', models.CharField(default='46470', max_length=10, verbose_name='C.P. emisor')),
                ('emisor_municipio', models.CharField(default='Albal (Valencia)', max_length=100, verbose_name='Municipio emisor')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='ListadoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, verbose_name='Nº Factura')),
                ('trimestre', models.PositiveIntegerField(verbose_name='Trimestre')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Neto (incorrecto)')),
                ('iva_incorrecto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='IVA declarado (incorrecto)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Listado Histórico',
                'verbose_name_plural': 'Listados Históricos',
                'ordering': ['anio', 'trimestre', 'numero_factura'],
                'unique_together': {('numero_factura', 'trimestre', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('AM', 'AM'), ('A1', 'A1'), ('A2', 'A2'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('C+E', 'C+E')], default='B', max_length=5, verbose_name='Curso')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Nº Factura')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nombre_factura', models.CharField(max_length=200, verbose_name='Nombre en factura')),
                ('dni_factura', models.CharField(blank=True, default='', max_length=20, verbose_name='DNI en factura')),
                ('direccion_factura', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección en factura')),
                ('cp_factura', models.CharField(blank=True, default='', max_length=10, verbose_name='C.P. en factura')),
                ('municipio_factura', models.CharField(blank=True, default='', max_length=100, verbose_name='Municipio en factura')),
                ('provincia_factura', models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia en factura')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Base Imponible')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='IVA')),
                ('tasas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Tasas')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total')),
                ('tasa_basica_qty', models.PositiveIntegerField(default=0, verbose_name='Tasa Básica (cant)')),
                ('tasa_a_qty', models.PositiveIntegerField(default=0, verbose_name='Tasa A (cant)')),
                ('traslado_qty', models.PositiveIntegerField(default=0, verbose_name='Traslado (cant)')),
                ('renovaciones_qty', models.PositiveIntegerField(default=0, verbose_name='Renovaciones (cant)')),
                ('trimestre', models.PositiveIntegerField(choices=[(1, '1er Trimestre'), (2, '2º Trimestre'), (3, '3er Trimestre'), (4, '4º Trimestre')], verbose_name='Trimestre')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='facturacion.alumno')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['anio', 'numero_factura'],
                'indexes': [models.Index(fields=['anio', 'trimestre'], name='facturacion_anio_31b62d_idx'), models.Index(fields=['numero_factura'], name='facturacion_numero__d0f299_idx'), models.Index(fields=['dni_factura'], name='facturacion_dni_fac_994419_idx')],
            },
        ),
    ]
